---
- name: common k8s libs and dependencies
  hosts: k8s
  become: true
  roles:
    - rpi-docker
    - { role: rpi-k8s, role_action: setup }

- name: setup k8s master
  hosts: k8s_master
  become: true
  roles:
    - { role: rpi-k8s, role_action: 'init master' }
  tags:
    - k8s-master

- name: join minions to k8s cluster
  hosts: k8s_minions
  become: true
  roles:
    - { role: rpi-k8s, role_action: 'join minions' }
  tags:
    - k8s-minions
...