---
- name: common k8s libs and dependencies
  hosts: k8s
  become: true
  roles:
    - { role: rpi-k8s, role_action: setup }
  tags:
    - k8s-setup

- name: pre-load k8s docker images
  hosts: k8s_master
  become: true
  roles:
    - { role: rpi-k8s, role_action: preload }

- name: setup k8s master
  hosts: k8s_master
  become: true
  roles:
    - { role: rpi-k8s, role_action: 'init master' }
  tags:
    - k8s-master

- name: setup flannel overlay network
  hosts: k8s_master
  become: true
  roles:
    - { role: rpi-k8s, role_action: 'setup flannel' }
  tags:
    - flannel

- name: join minions to k8s cluster
  hosts: k8s_minions
  become: true
  roles:
    - { role: rpi-k8s, role_action: 'join minions' }
  tags:
    - k8s-minions

- name: deploy kubernetes dashboard
  hosts: k8s_master
  become: true
  roles:
    - { role: rpi-k8s, role_action: 'deploy dashboard' }
  tags:
    - k8s-dashboard
...
