---
- name: create k8s flannel template
  template:
    src: kube-flannel.yml.erb
    dest: /tmp/kube-flannel.yml

- name: launch flannel daemonset
  command: kubectl apply -f /tmp/kube-flannel.yml
...