---
- name: check kubelet service is running
  systemd:
    name: kubelet
    state: started

- name: stat kubelet config
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: create cni plugin directory
  file:
    path: /etc/cni/net.d
    owner: root
    group: root
    state: directory

- name: create default cni configuration
  copy:
    dest: /etc/cni/net.d/10-flannel.conf
    owner: root
    group: root
    src: flannel.conf

- name: run kubeadm init on master
  shell: |
    kubeadm init \
      --token {{ k8s_token }} \
      --use-kubernetes-version={{ k8s_version_label }} \
      --pod-network-cidr={{ k8s_pod_network }}
  when: not kubelet_conf.stat.exists
  register: k8s_init

- name: fetch admin.conf to local machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.k8s/admin.conf
  when: k8s_init|changed
...
