---
- name: setup software packages
  include: setup.yml
  when: role_action == 'setup'

- name: preload docker images
  include: preload.yml
  when: role_action == 'preload'

- name: initialize k8s master
  include: init.yml
  when: role_action == 'init master'

- name: setup flannel
  include: flannel.yml
  when: role_action == 'setup flannel'

- name: join k8s cluster
  include: join.yml
  when: role_action == 'join minions'

- name: setup k8s dashboard
  include: dashboard.yml
  when: role_action == 'deploy dashboard'
...
