---
- name: install common debian packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - iperf
    - wavemon
    - python-setuptools

- name: uninstall apt pip package
  become: true
  apt:
    name: python-pip
    state: absent

- name: install latest pip using easy_install
  become: true
  easy_install:
    name: pip
