---
- name: install common debian packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - iperf
    - wavemon
    - python-setuptools

- name: install latest pip
  become: true
  easy_install:
    name: pip
